sudo: false

language: python
python:
  - "3.5"

addons:
  postgresql: "9.4"

services:
  - postgresql

env:
  global:
    - DB_URL="postgres:///finance"
    - TEST_DB_URL="postgres:///finance"
    - PYTHONPATH=.

jobs:
  include:
    - stage: build
      install:
        - pip install -r requirements.txt
        - pip install -r tests/requirements.txt
        - pip install -e .
      before_script:
        - psql -c 'CREATE DATABASE finance;' -U postgres
        - finance create_all
      script:
        - py.test -v tests --cov finance --cov-report term-missing
      after_success:
        - coveralls
